# Generated by Django 4.1.7 on 2023-03-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_ID', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('mid_term', models.DateTimeField(verbose_name='mid term')),
                ('final', models.DateTimeField(verbose_name='final')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_num', models.IntegerField()),
                ('day', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('teacher', models.CharField(max_length=200)),
                ('subject_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.subject')),
            ],
        ),
    ]
