# Generated by Django 4.1.7 on 2023-03-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='User',
        ),
    ]
