# Generated by Django 4.1.7 on 2023-03-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpApp', '0002_alter_subject_final_alter_subject_mid_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_ID',
            field=models.CharField(max_length=200),
        ),
    ]
