# Generated by Django 4.1.7 on 2023-03-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpApp', '0003_alter_subject_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='final'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='mid_term',
            field=models.DateTimeField(blank=True, null=True, verbose_name='mid term'),
        ),
    ]
