# Generated by Django 4.1.7 on 2023-03-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpApp', '0004_alter_subject_final_alter_subject_mid_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='final',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='mid_term',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
