# Generated by Django 4.1.7 on 2023-03-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpApp', '0005_alter_subject_final_alter_subject_mid_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sec_num',
            field=models.CharField(max_length=200),
        ),
    ]
