# Generated by Django 4.1.7 on 2023-03-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpApp', '0006_alter_section_sec_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='end_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='start_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
