# Generated by Django 4.1.7 on 2023-03-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpApp', '0007_section_end_time_section_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='final_term_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='final_term_end_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='final_term_start_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='mid_term_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='mid_term_end_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='mid_term_start_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
