# Generated by Django 4.1.7 on 2023-03-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_alter_user_subject_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
